

CREATE TABLE T_CONSULTA(codigo_co INT PRIMARY KEY AUTO_INCREMENT, data_co date, cliente INT, nutricionista INT);

INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-30', '1', '1' );
INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-29', '2', '2' );
INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-29', '3', '2' );
INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-30', '4', '3' );
INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-30', '5', '5' );
INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-30', '6', '1' );
INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-29', '7', '1' );
INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-29', '8', '2' );
INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-30', '9', '3' );
INSERT INTO T_CONSULTA (data_co, cliente, nutricionista) VALUE ('2018-10-30', '10', '1' );
